services:
  crystalline:
    image: codeberg.org/kryesh/crystalline:latest
    hostname: crystalline
    restart: unless-stopped
    volumes:
      - ./bootstrap.json:/config/bootstrap.json:ro
      - crystalline_data:/data
      - crystalline_config:/config
      - type: tmpfs
        target: /cache
      - ./rulesets:/rulesets:ro
    ports:
      - 8080:8080
    environment:
      - CRYSTALLINE_BOOTSTRAP_CONFIG=/config/bootstrap.json
  fluentbit:
    image: fluent/fluent-bit
    ports:
      - 5140:5140
    volumes:
      - ./fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - fluentbit_state:/state

volumes:
  crystalline_data:
  crystalline_config:
  fluentbit_state:
